options:
    prefix: &d&lᴋᴜᴘᴀʟᴍᴄ &r&7- &fᴛʀᴀɪᴛꜱ &7| &r

on portal:
    cancel event
    
# =================================== GLOBAL RULES =================================================
    
# CRAFTING HUNGER COST
on craft:
    set {_cost} to 0.5
    if player has permission "ethnicity.kapampangan":
        stop
    
    set {_hunger} to player's food level
    
    if {_hunger} <= 1:
        cancel event
        send "{@prefix}&cʏᴏᴜ ᴀʀᴇ ᴛᴏᴏ ʜᴜɴɢʀʏ ᴛᴏ ᴄʀᴀꜰᴛ. ᴇᴀᴛ ꜱᴏᴍᴇᴛʜɪɴɢ ꜰɪʀꜱᴛ."
        stop
    
    if player has permission "ethnicity.bicolano":
        set {_cost} to 1
        send "{@prefix}&7ᴄʀᴀꜰᴛɪɴɢ ᴄᴏꜱᴛꜱ ʏᴏᴜ ᴀ ʜᴜɴɢᴇʀ ʙᴀʀ."
        stop
        
    set player's food level to {_hunger} - {_cost}
    send "{@prefix}&7ᴄʀᴀꜰᴛɪɴɢ ᴄᴏꜱᴛꜱ ʏᴏᴜ ᴀ ʜᴀʟꜰ ʜᴜɴɢᴇʀ ʙᴀʀ."
    
#  DISABLE MILK
on consume of milk bucket:
    cancel event


# DISABLE RIPTIDE
on inventory click:
    if event-inventory is an anvil inventory:
        if clicked slot is 2:
            if event-item is set:
                if event-item is enchanted with riptide:
                    cancel event
                    set repair cost of event-inventory to 0
                    send "&cʀɪᴘᴛɪᴅᴇ ɪꜱ ɴᴏᴛ ᴀʟʟᴏᴡᴇᴅ." to player

on inventory close:
    loop items in player's inventory:
        if loop-item is enchanted with riptide:
            remove loop-item from player's inventory
            give 1 trident to player
            send "&cʀɪᴘᴛɪᴅᴇ ʜᴀꜱ ʙᴇᴇɴ ʀᴇᴍᴏᴠᴇᴅ ꜰʀᴏᴍ ʏᴏᴜʀ ɪɴᴠᴇɴᴛᴏʀʏ." to player

# DISABLE TRIDENT ON ENCHANTMENT TABLE
on enchant:
    if event-item is trident:
        cancel event
        send "&cᴛʀɪᴅᴇɴᴛ ɪꜱ ᴅɪꜱᴀʙʟᴇᴅ ᴏɴ ᴇɴᴄʜᴀɴᴛᴍᴇɴᴛ ᴛᴀʙʟᴇ" to player

# MACE DENSITY CD
on damage:
    attacker is a player

    set {_item} to attacker's tool
    if type of {_item} is mace:
        set {_density} to enchantment level of density on {_item}

        if {_density} > 0:
            if {densityCooldown::%attacker's uuid%} is set:
                if difference between now and {densityCooldown::%attacker's uuid%} < 5 minutes:
                    cancel event
                    send "&cʏᴏᴜʀ ᴅᴇɴꜱɪᴛʏ ᴍᴀᴄᴇ ɪꜱ ᴏɴ ᴄᴏᴏʟᴅᴏᴡɴ!" to attacker
                    stop
            set {densityCooldown::%attacker's uuid%} to now

       
# MILK BUCKET SYSTEM 
on right click on entity:
    if clicked entity is a player:
        if player's held item is a bucket:
            set {_target} to clicked entity
            set {_target_name} to {_target}'s name
            
            set {_milk_bucket} to milk bucket
            set display name of {_milk_bucket} to "&f%{_target_name}%'ꜱ ᴍɪʟᴋ"
            
            remove 1 bucket from player's inventory
            if player can hold {_milk_bucket}:
                give {_milk_bucket} to player
                send "&a✓ &fʏᴏᴜ ᴍɪʟᴋᴇᴅ &a%{_target_name}%!" to player
            else:
                give 1 bucket to player
                send "&c✗ &fʏᴏᴜʀ ɪɴᴠᴇɴᴛᴏʀʏ ɪꜱ ꜰᴜʟʟ!!" to player
                
# GATA HARVEST
on right click on jungle log:
    if player's tool is a bucket:
        remove 1 bucket from player's inventory
        give player a milk bucket named "&fGata"


# =================================== COMBAT LOG =================================================

on damage:
    attacker is player
    victim is player

    set {_player1} to attacker
    set {_player2} to victim    

    if {_player1} is not {_player2}:
        if {_player1} does not have permission "*":
            if {_player1} does not have permission "combatlog.active":
                execute console command "lp user %{_player1}% permission settemp combatlog.active true 15s"
        else:
            if {_player1} has permission "*":
                send "{@prefix-2}&cOP Players are immune to combat log" to {_player1}

        if {_player2} does not have permission "*":                          
            if {_player2} does not have permission "combatlog.active":
                execute console command "lp user %{_player2}% permission settemp combatlog.active true 15s"        
        else:
            if {_player2} has permission "*":
                send "{@prefix-2}&cOP Players are immune to combat log" to {_player2}
            
            
on quit:
    if player does not have permission "*":
        if player has permission "combatlog.active":
            execute console command "lp user %player% permission set combatlog.punish true"
            broadcast "{@prefix}&a%player% &cleft while in combat!"


on join:
    wait 10 ticks
    delete {combatlog.timer.%player%}
    if player does not have permission "*":
        if player has permission "combatlog.punish":
            broadcast "{@prefix-2}Combatlog Punish Event for %player%"
            execute console command "lp user %player% permission unset combatlog.punish"
            set player's health to 0


every 1 second:
    loop all players:
        if loop-player does not have permission "*":
            if loop-player has permission "combatlog.active":
                if {combatlog.timer.%loop-player%} is not set:
                    set {combatlog.timer.%loop-player%} to 15
                else:
                    subtract 1 from {combatlog.timer.%loop-player%}
                
                if {combatlog.timer.%loop-player%} > 0:
                    send action bar "ɪɴ ᴄᴏᴍʙᴀᴛ: &c%{combatlog.timer.%loop-player%}%s" to loop-player
                else:
                    execute console command "lp user %loop-player% permission unsettemp combatlog.active"
                    delete {combatlog.timer.%loop-player%}

    
