name: Ixpu-CoordsSync
version: 1.2.0
main: dev.ixpu.coordssync.CoordsSync
description: Multi-server coordinate synchronization using Redis
authors: [ixpu]
website: https://github.com/expo-sitory
api-version: "1.21"

commands:
  coordssync:
    description: CoordsSync admin command
    usage: /coordssync [reload|status]
    aliases: [cs]
    permission: coordssync.admin

permissions:
  coordssync.admin:
    description: Allows access to CoordsSync admin commands
    default: op
  
  coordssync.use:
    description: Allows players to be teleported to their saved location on join
    default: false