# Rune Tree Selection Backend
on load:
    # Main Rune Paths
    set {primary-rune-path::*} to ("precision", "domination", "resolve", "inspriration", "sorcery")
    # Secondary Rune Paths
    set {secondary-rune-path::*} to ("precision", "domination", "resolve", "inspriration", "sorcery")

    # Rune Keystones

    set {rune-keystones::*} to ("press-the-attack", "lethal-tempo", "fleet-footwork", "conqueror", "electrocute", "dark-harvest", "hail-of-blades", "grasp-of-the-undying", "aftershock", "guardian", "summon-aery", "arcane-commet", "storm-raider-surge", "hell-fire-torch", "glacial-augment", "unsealed-spellbook", "first-strike")

    # Prinary Slots

    set {primary-slot-1::*} to ("absorb-life", "triump", "presence-of-mind", "cheap-shot", "taste-of-blood", "sudden-impact", "demolish", "font-of-life", "shield-bash", "axiom-arcanist", "manaflow-band", "nimbus-cloak", "hextech-flashtraption", "magical-footwear", "cash-back")
    set {primary-slot-2::*} to ("legend-alacrity", "legend-haste", "legend-bloodline", "six-sense", "grisly-mementos", "deep-ward", "conditioning", "second-wind", "bone-plating", "trascendence", "celerity", "absolute-focus", "tripple-tonic", "time-warp-tonic", "biscuit-delivery")
    set {primary-slot-3::*} to ("coup-de-grace", "cut-down", "last-stand", "treasure-hunter", "relentless-hunter", "ultimate-hunter", "overgrowth", "revitalize", "unflinching", "scorch", "water-walking", "gathering-storm", "cosmic-insight", "approach-velocity", "jack-of-all-trades")

    # Secondary Slots

    set {precision-secondary-slot-1::*} to ("absorb-life", "triump", "presence-of-mind", "legend-alacrity", "legend-haste", "legend-bloodline", "coup-de-grace", "cut-down", "last-stand")
    set {precision-secondary-slot-2::*} to ("absorb-life", "triump", "presence-of-mind", "legend-alacrity", "legend-haste", "legend-bloodline", "coup-de-grace", "cut-down", "last-stand")

    set {domination-secondary-slot-1::*} to ("cheap-shot", "taste-of-blood", "sudden-impact", "six-sense", "grisly-mementos", "deep-ward", "treasure-hunter", "relentless-hunter", "ultimate-hunter")
    set {domination-secondary-slot-2::*} to ("cheap-shot", "taste-of-blood", "sudden-impact", "six-sense", "grisly-mementos", "deep-ward", "treasure-hunter", "relentless-hunter", "ultimate-hunter")

    set {resolve-secondary-slot-1::*} to ("demolish", "font-of-life", "shield-bash", "conditioning", "second-wind", "bone-plating", "overgrowth", "revitalize", "unflinching")
    set {resolve-secondary-slot-2::*} to ("demolish", "font-of-life", "shield-bash", "conditioning", "second-wind", "bone-plating", "overgrowth", "revitalize", "unflinching")

    set {sorcery-secondary-slot-1::*} to ("axiom-arcanist", "manaflow-band", "nimbus-cloak", "trascendence", "celerity", "absolute-focus", "scorch", "water-walking", "gathering-storm")
    set {sorcery-secondary-slot-2::*} to ("axiom-arcanist", "manaflow-band", "nimbus-cloak", "trascendence", "celerity", "absolute-focus", "scorch", "water-walking", "gathering-storm")

    set {inspiration-secondary-slot-1::*} to ("hextech-flashtraption", "magical-footwear", "cash-back", "tripple-tonic", "time-warp-tonic", "biscuit-delivery", "cosmic-insight", "approach-velocity", "jack-of-all-trades")
    set {inspiration-secondary-slot-2::*} to ("hextech-flashtraption", "magical-footwear", "cash-back", "tripple-tonic", "time-warp-tonic", "biscuit-delivery", "cosmic-insight", "approach-velocity", "jack-of-all-trades")

every 1 second:
    loop all players:
        set {_magic-resist::%loop-player's uuid%} to 0
        set {_active-armor::%loop-player's uuid%} to 0
        set {_attack-speed::%loop-player's uuid%} to 0
        set {_ability-power::%loop-player's uuid%} to 0
        set {_attack-damage::%loop-player's uuid%} to 0
        set {_item-cd-haste::%loop-player's uuid%} to 0

on tab complete of "/runes":
    set tab completions for position 1 to "select" and "clear" and "show"

    if tab arg-1 is "select":
        set tab completions for position 2 to "primary" and "secondary"
        # PRIMARY RUNES
        if tab arg-2 is "primary":
            set tab completions for position 3 to "precision" and "domination" and "resolve" and "sorcery" and "inspiration"
            if tab arg-3 is "precision":
                set tab completions for position 4 to "press-the-attack" and "lethal-tempo" and "fleet-footwork" and "conqueror"
                if tab arg-4 is "press-the-attack" or "lethal-tempo" or "fleet-footwork" or "conqueror":
                    set tab completions for position 5 to "absorb-life" and "triump" and "presence-of-mind"
                    if tab arg-5 is "absorb-life" or "triump" or "presence-of-mind":
                        set tab completions for position 6 to "legend-alacrity" and "legend-haste" and "legend-bloodline"
                        if tab arg-6 is "legend-alacrity" or "legend-haste" or "legend-bloodline":
                            set tab completions for position 7 to "coup-de-grace" and "cut-down" and "last-stand"       

            else if tab arg-3 is "domination":
                set tab completions for position 4 to "electrocute" and "dark-harvest" and "hail-of-blades"
                if tab arg-4 is "electrocute" or "dark-harvest" or "hail-of-blades":
                    set tab completions for position 5 to "cheap-shot" and "taste-of-blood" and "sudden-impact"
                    if tab arg-5 is "cheap-shot" or "taste-of-blood" or "sudden-impact":
                        set tab completions for position 6 to "six-sense" and "grisly-mementos" and "deep-ward"
                        if tab arg-6 is "six-sense" or "grisly-mementos" or "deep-ward":
                            set tab completions for position 7 to "treasure-hunter" and "relentless-hunter" and "ultimate-hunter"
                                
            else if tab arg-3 is "resolve":
                set tab completions for position 4 to "grasp-of-the-undying" and "aftershock" and "guardian"
                if tab arg-4 is "grasp-of-the-undying" or "aftershock" or "guardian":
                    set tab completions for position 5 to "demolish" and "font-of-life" and "shield-bash"
                    if tab arg-5 is "demolish" or "font-of-life" or "shield-bash":
                        set tab completions for position 6 to "conditioning" and "second-wind" and "bone-plating"
                        if tab arg-6 is "conditioning" or "second-wind" or "bone-plating":
                            set tab completions for position 7 to "overgrowth" and "revitalize" and "unflinching"
            
            else if tab arg-3 is "sorcery":
                set tab completions for position 4 to "summon-aery" and "arcane-commet" and "storm-raider-surge" and "hell-fire-torch"
                if tab arg-4 is "summon-aery" or "arcane-commet" or "storm-raider-surge" or "hell-fire-torch":
                    set tab completions for position 5 to "axiom-arcanist" and "manaflow-band" and "nimbus-cloak"
                    if tab arg-5 is "axiom-arcanist" or "manaflow-band" or "nimbus-cloak":
                        set tab completions for position 6 to "trascendence" and "celerity" and "absolute-focus"
                        if tab arg-6 is "trascendence" or "celerity" or "absolute-focus":
                            set tab completions for position 7 to "scorch" and "water-walking" and "gathering-storm"
            
            else if tab arg-3 is "inspiration":
                set tab completions for position 4 to "glacial-augment" and "unsealed-spellbook" and "first-strike"
                if tab arg-4 is "glacial-augment" or "unsealed-spellbook" or "first-strike":
                    set tab completions for position 5 to "hextech-flashtraption" and "magical-footwear" and "cash-back"
                    if tab arg-5 is "hextech-flashtraption" or "magical-footwear" or "cash-back":
                        set tab completions for position 6 to "tripple-tonic" and "time-warp-tonic" and "biscuit-delivery"
                        if tab arg-6 is "tripple-tonic" or "time-warp-tonic" or "biscuit-delivery":
                            set tab completions for position 7 to "cosmic-insight" and "approach-velocity" and "jack-of-all-trades"

        # SECONDARY RUNES
        else if tab arg-2 is "secondary":
            set tab completions for position 3 to "precision" and "domination" and "resolve" and "sorcery" and "inspiration"
            if tab arg-3 is "precision":
                set tab completions for position 4 to "absorb-life" and "triump" and "presence-of-mind" and "legend-alacrity" and "legend-haste" and "legend-bloodline" and "coup-de-grace" and "cut-down" and "last-stand"

                # IF SLOT 1
                if tab arg-4 is "absorb-life" or "triump" or "presence-of-mind":
                    set tab completions for position 5 to "legend-alacrity" and "legend-haste" and "legend-bloodline" and "coup-de-grace" and "cut-down" and "last-stand"
                # IF SLOT 2
                else if tab arg-4 is "legend-alacrity" or "legend-haste" or "legend-bloodline":
                    set tab completions for position 5 to "absorb-life" and "triump" and "presence-of-mind" and "coup-de-grace" and "cut-down" and "last-stand"  
                # IF SLOT 3
                else if tab arg-4 is "coup-de-grace" or "cut-down" or "last-stand":
                    set tab completions for position 5 to "absorb-life" and "triump" and "presence-of-mind" and "legend-alacrity" and "legend-haste" and "legend-bloodline"

            else if tab arg-3 is "domination":
                set tab completions for position 4 to "cheap-shot" and "taste-of-blood" and "sudden-impact" and "six-sense" and "grisly-mementos" and "deep-ward" and "treasure-hunter" and "relentless-hunter" and "ultimate-hunter"

                # IF SLOT 1
                if tab arg-4 is "cheap-shot" or "taste-of-blood" or "sudden-impact":
                    set tab completions for position 5 to "six-sense" and "grisly-mementos" and "deep-ward" and "treasure-hunter" and "relentless-hunter" and "ultimate-hunter"
                  
                # IF SLOT 2
                else if tab arg-4 is "six-sense" or "grisly-mementos" or "deep-ward":
                    set tab completions for position 5 to "cheap-shot" and "taste-of-blood" and "sudden-impact" and "treasure-hunter" and "relentless-hunter" and "ultimate-hunter"

                # IF SLOT 3
                else if tab arg-4 is "treasure-hunter" or "relentless-hunter" or "ultimate-hunter":
                    set tab completions for position 5 to "cheap-shot" and "taste-of-blood" and "sudden-impact" and "six-sense" and "grisly-mementos" and "deep-ward" 

            else if tab arg-3 is "resolve":
                set tab completions for position 4 to "demolish" and "font-of-life" and "shield-bash" and "conditioning" and "second-wind" and "bone-plating" and "overgrowth" and "revitalize" and "unflinching"

                # IF SLOT 1
                if tab arg-4 is "demolish" or "font-of-life" or "shield-bash":
                    set tab completions for position 5 to "conditioning" and "second-wind" and "bone-plating" and "overgrowth" and "revitalize" and "unflinching"

                # IF SLOT 2
                else if tab arg-4 is "conditioning" or "second-wind" or "bone-plating":
                    set tab completions for position 5 to "overgrowth" and "revitalize" and "unflinching" and "demolish" and "font-of-life" and "shield-bash"

                # IF SLOT 3
                else if tab arg-4 is "overgrowth" or "revitalize" or "unflinching":
                    set tab completions for position 5 to "demolish" and "font-of-life" and "shield-bash" and "conditioning" and "second-wind" and "bone-plating"
            
            else if tab arg-3 is "sorcery":
                set tab completions for position 4 to "axiom-arcanist" and "manaflow-band" and "nimbus-cloak" and "trascendence" and "celerity" and "absolute-focus" and "scorch" and "water-walking" and "gathering-storm"

                # IF SLOT 1
                if tab arg-4 is "axiom-arcanist" or "manaflow-band" or "nimbus-cloak":
                    set tab completions for position 5 to "trascendence" and "celerity" and "absolute-focus" and "scorch" and "water-walking" and "gathering-storm"

                # IF SLOT 2
                else if tab arg-4 is "trascendence" or "celerity" or "absolute-focus":
                    set tab completions for position 5 to "axiom-arcanist" and "manaflow-band" and "nimbus-cloak" and "scorch" and "water-walking" and "gathering-storm"

                # IF SLOT 3
                else if tab arg-4 is "scorch" or "water-walking" or "gathering-storm":
                    set tab completions for position 5 to "axiom-arcanist" and "manaflow-band" and "nimbus-cloak" and "trascendence" and "celerity" and "absolute-focus"        
           
            else if tab arg-3 is "inspiration":
                set tab completions for position 4 to "hextech-flashtraption" and "magical-footwear" and "cash-back" and "tripple-tonic" and "time-warp-tonic" and "biscuit-delivery" and "cosmic-insight" and "approach-velocity" and "jack-of-all-trades"

                # IF SLOT 1
                if tab arg-4 is "hextech-flashtraption" or "magical-footwear" or "cash-back":
                    set tab completions for position 5 to "tripple-tonic" and "time-warp-tonic" and "biscuit-delivery" and "cosmic-insight" and "approach-velocity" and "jack-of-all-trades"

                # IF SLOT 2
                else if tab arg-4 is "tripple-tonic" or "time-warp-tonic" or "biscuit-delivery":
                    set tab completions for position 5 to "hextech-flashtraption" and "magical-footwear" and "cash-back" and "cosmic-insight" and "approach-velocity" and "jack-of-all-trades"

                # IF SLOT 3
                else if tab arg-4 is "cosmic-insight" or "approach-velocity" or "jack-of-all-trades":
                    set tab completions for position 5 to "hextech-flashtraption" and "magical-footwear" and "cash-back" and "tripple-tonic" and "time-warp-tonic" and "biscuit-delivery"

command /runes [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>]:
    trigger:
        if arg-1 is "select":
            set {_current-primary-rune-path} to ""
            set {_current-secondary-rune-path} to ""            

            set {_current-rune-keystone} to ""

            set {_current-primary.slot-1} to ""
            set {_current-primary.slot-2} to ""
            set {_current-primary.slot-3} to ""

            set {_current-secondary.slot-1} to ""
            set {_current-secondary.slot-2} to ""

            if arg-2 is "primary":
                loop {primary-rune-path::*}:
                    if arg-3 is loop-value:
                        set {_current-primary-rune-path} to loop-value
                        stop loop

                loop {rune-keystones::*}:
                    if arg-4 is loop-value:
                        set {_current-rune-keystone} to loop-value
                        stop loop

                loop {primary-slot-1::*}:
                    if arg-5 is loop-value:
                        set {_current-primary.slot-1} to loop-value
                        stop loop

                loop {primary-slot-2::*}:
                    if arg-6 is loop-value:
                        set {_current-primary.slot-2} to loop-value
                        stop loop

                loop {primary-slot-3::*}:
                    if arg-7 is loop-value:
                        set {_current-primary.slot-3} to loop-value
                        stop loop               

                execute console command "lp user %player% permission set primary-rune-path.%{_current-primary-rune-path}% true"                
                execute console command "lp user %player% permission set rune-keystone.%{_current-rune-keystone}% true"
                execute console command "lp user %player% permission set primary-rune.slot-1.%{_current-primary.slot-1}% true"
                execute console command "lp user %player% permission set primary-rune.slot-2.%{_current-primary.slot-2}% true"
                execute console command "lp user %player% permission set primary-rune.slot-3.%{_current-primary.slot-3}% true"                             

            else if arg-2 is "secondary":
                loop {secondary-rune-path::*}:
                    if arg-3 is loop-value:
                        set {_current-secondary-rune-path} to loop-value
                        stop loop

                execute console command "lp user %player% permission set secondary-rune-path.%{_current-secondary-rune-path}% true"         
                send "&a%{_current-secondary-rune-path}%" to the console  
             
                if {_current-secondary-rune-path} is "precision":
                    loop {precision-secondary-slot-1::*}:
                        if arg-4 is loop-value:
                            set {_current-secondary.slot-1} to loop-value
                            stop loop

                    loop {precision-secondary-slot-2::*}:
                        if arg-5 is loop-value:
                            set {_current-secondary.slot-2} to loop-value
                            stop loop       

                    execute console command "lp user %player% permission set secondary-rune.slot-1.%{_current-secondary.slot-1}% true" 
                    execute console command "lp user %player% permission set secondary-rune.slot-2.%{_current-secondary.slot-2}% true"                                                                                             
                    
                else if {_current-secondary-rune-path} is "domination":
                    loop {domination-secondary-slot-1::*}:
                        if arg-4 is loop-value:
                            set {_current-secondary.slot-1} to loop-value
                            stop loop

                    loop {domination-secondary-slot-2::*}:
                        if arg-5 is loop-value:
                            set {_current-secondary.slot-2} to loop-value
                            stop loop            

                    execute console command "lp user %player% permission set secondary-rune.slot-1.%{_current-secondary.slot-1}% true" 
                    execute console command "lp user %player% permission set secondary-rune.slot-2.%{_current-secondary.slot-2}% true"                                                   

                else if {_current-secondary-rune-path} is "resolve":
                    loop {resolve-secondary-slot-1::*}:
                        if arg-4 is loop-value:
                            set {_current-secondary.slot-1} to loop-value
                            stop loop

                    loop {resolve-secondary-slot-2::*}:
                        if arg-5 is loop-value:
                            set {_current-secondary.slot-2} to loop-value
                            stop loop    

                    execute console command "lp user %player% permission set secondary-rune.slot-1.%{_current-secondary.slot-1}% true" 
                    execute console command "lp user %player% permission set secondary-rune.slot-2.%{_current-secondary.slot-2}% true"                                           

                else if {_current-secondary-rune-path} is "sorcery":
                    loop {sorcery-secondary-slot-1::*}:
                        if arg-4 is loop-value:
                            set {_current-secondary.slot-1} to loop-value
                            stop loop
                    
                    loop {sorcery-secondary-slot-2::*}:
                        if arg-5 is loop-value:
                            set {_current-secondary.slot-2} to loop-value
                            stop loop

                    execute console command "lp user %player% permission set secondary-rune.slot-1.%{_current-secondary.slot-1}% true" 
                    execute console command "lp user %player% permission set secondary-rune.slot-2.%{_current-secondary.slot-2}% true"

                else if {_current-secondary-rune-path} is "inspiration":
                    loop {inspiration-secondary-slot-1::*}:
                        if arg-4 is loop-value:
                            set {_current-secondary.slot-1} to loop-value
                            stop loop

                    loop {inspiration-secondary-slot-2::*}:
                        if arg-5 is loop-value:
                            set {_current-secondary.slot-2} to loop-value
                            stop loop         
                    
                    execute console command "lp user %player% permission set secondary-rune.slot-1.%{_current-secondary.slot-1}% true" 
                    execute console command "lp user %player% permission set secondary-rune.slot-2.%{_current-secondary.slot-2}% true"                                                                          

        else if arg-1 is "show":
            set {_current-primary-rune-path} to ""
            set {_current-secondary-rune-path} to ""            

            set {_current-rune-keystone} to ""

            set {_current-primary.slot-1} to ""
            set {_current-primary.slot-2} to ""
            set {_current-primary.slot-3} to ""

            set {_current-secondary.slot-1} to ""
            set {_current-secondary.slot-2} to ""

            loop {primary-rune-path::*}:
                if player has permission "primary-rune-path.%loop-value%":
                    set {_current-primary-rune-path} to loop-value
                    stop loop            

            loop {secondary-rune-path::*}:
                if player has permission "secondary-rune-path.%loop-value%":
                    set {_current-secondary-rune-path} to loop-value
                    stop loop            

            loop {rune-keystones::*}:
                if player has permission "rune-keystone.%loop-value%": 
                    set {_current-rune-keystone} to loop-value
                    stop loop

            loop {primary-slot-1::*}:
                if player has permission "primary-rune.slot-1.%loop-value%":
                    set {_current-primary.slot-1} to loop-value
                    stop loop

            loop {primary-slot-2::*}:
                if player has permission "primary-rune.slot-2.%loop-value%":
                    set {_current-primary.slot-2} to loop-value
                    stop loop

            loop {primary-slot-3::*}:
                if player has permission "primary-rune.slot-3.%loop-value%":
                    set {_current-primary.slot-3} to loop-value
                    stop loop

            if {_current-secondary-rune-path} is "precision":
                loop {precision-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {precision-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop   

            else if {_current-secondary-rune-path} is "domination":             

                loop {domination-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {domination-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop  

            else if {_current-secondary-rune-path} is "resolve":            

                loop {resolve-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {resolve-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop        

            else if {_current-secondary-rune-path} is "sorcery":        

                loop {sorcery-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {sorcery-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop         

            else if {_current-secondary-rune-path} is "inspriration":

                loop {inspiration-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {inspiration-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop               
            
            send "&c═════ &f[ &e&lᴀᴄᴛɪᴠᴇ ʀᴜɴᴇꜱ &r] &c═════" to player
            send "ᴘʀɪᴍᴀʀʏ ʀᴜɴᴇ ᴘᴀᴛʜ: &e%{_current-primary-rune-path}%" to player
            send "ʀᴜɴᴇ ᴋᴇʏꜱᴛᴏɴᴇ: &e%{_current-rune-keystone}%" to player
            send "ᴘʀɪᴍᴀʀʏ ꜱʟᴏᴛ 1: &e%{_current-primary.slot-1}%" to player
            send "ᴘʀɪᴍᴀʀʏ ꜱʟᴏᴛ 2: &e%{_current-primary.slot-2}%" to player     
            send "ᴘʀɪᴍᴀʀʏ ꜱʟᴏᴛ 3: &e%{_current-primary.slot-3}%" to player
            send "" to player
            send "ꜱᴇᴄᴏɴᴅᴀʀʏ ʀᴜɴᴇ ᴘᴀᴛʜ: &e%{_current-secondary-rune-path}%" to player
            send "ꜱᴇᴄᴏɴᴅᴀʀʏ ꜱʟᴏᴛ 1: &e%{_current-secondary.slot-1}%" to player
            send "ꜱᴇᴄᴏɴᴅᴀʀʏ ꜱʟᴏᴛ 2: &e%{_current-secondary.slot-2}%" to player
            send "&c══════════════════════" to player

        
        else if arg-1 is "clear":
            set {_current-primary-rune-path} to ""
            set {_current-secondary-rune-path} to ""            

            set {_current-rune-keystone} to ""

            set {_current-primary.slot-1} to ""
            set {_current-primary.slot-2} to ""
            set {_current-primary.slot-3} to ""

            set {_current-secondary.slot-1} to ""
            set {_current-secondary.slot-2} to ""

            loop {primary-rune-path::*}:
                if player has permission "primary-rune-path.%loop-value%":
                    set {_current-primary-rune-path} to loop-value
                    stop loop            

            loop {secondary-rune-path::*}:
                if player has permission "secondary-rune-path.%loop-value%":
                    set {_current-secondary-rune-path} to loop-value
                    stop loop            

            loop {rune-keystones::*}:
                if player has permission "rune-keystone.%loop-value%": 
                    set {_current-rune-keystone} to loop-value
                    stop loop

            loop {primary-slot-1::*}:
                if player has permission "primary-rune.slot-1.%loop-value%":
                    set {_current-primary.slot-1} to loop-value
                    stop loop

            loop {primary-slot-2::*}:
                if player has permission "primary-rune.slot-2.%loop-value%":
                    set {_current-primary.slot-2} to loop-value
                    stop loop

            loop {primary-slot-3::*}:
                if player has permission "primary-rune.slot-3.%loop-value%":
                    set {_current-primary.slot-3} to loop-value
                    stop loop

            if {_current-secondary-rune-path} is "precision":
                loop {precision-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {precision-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop                

            else if {_current-secondary-rune-path} is "domination":
                loop {domination-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {domination-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop              

            else if {_current-secondary-rune-path} is "resolve":
                loop {resolve-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {resolve-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop                

            else if {_current-secondary-rune-path} is "sorcery":
                loop {sorcery-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {sorcery-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop              

            else if {_current-secondary-rune-path} is "inspiration":
                loop {inspiration-secondary-slot-1::*}:
                    if player has permission "secondary-rune.slot-1.%loop-value%":
                        set {_current-secondary.slot-1} to loop-value
                        stop loop

                loop {inspiration-secondary-slot-2::*}:
                    if player has permission "secondary-rune.slot-2.%loop-value%":
                        set {_current-secondary.slot-2} to loop-value
                        stop loop 

            execute console command "lp user %player% permission unset primary-rune-path.%{_current-primary-rune-path}%"
            execute console command "lp user %player% permission unset secondary-rune-path.%{_current-secondary-rune-path}%"
            execute console command "lp user %player% permission unset rune-keystone.%{_current-rune-keystone}%"
            execute console command "lp user %player% permission unset primary-rune.slot-1.%{_current-primary.slot-1}%"
            execute console command "lp user %player% permission unset primary-rune.slot-2.%{_current-primary.slot-2}%"
            execute console command "lp user %player% permission unset primary-rune.slot-3.%{_current-primary.slot-3}%"
            execute console command "lp user %player% permission unset secondary-rune.slot-1.%{_current-secondary.slot-1}%"
            execute console command "lp user %player% permission unset secondary-rune.slot-2.%{_current-secondary.slot-2}%"



            

                    
                
      
                        
                 
